title: The Future is Closer
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6568206
  brandStrength: 0.2870524537283927
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.6525242
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/66518be9-c20f-4a81-a3ff-4f9ca0436e30.svg
name: Nandi Nobell
author:
  name: Nandi Nobell
  email: nandi.nobell@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d09107c7-c310-42fb-8847-c4fe70dc5bf7.svg
typography_spectrum: 0.697637
layout_spectrum: 0.9586466
