typography_spectrum: 0.894918748177588
color:
  brandStrength: 0.2870524537283927
  lightness: 0.7277731958311051
  saturation: 0.7350078825838864
  rhythmicContrast: 0.26122072455473244
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.2875583420973271
author:
  name: Nandi Nobell
  email: nandi.nobell@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d09107c7-c310-42fb-8847-c4fe70dc5bf7.svg
name: Nandi Nobell
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/66518be9-c20f-4a81-a3ff-4f9ca0436e30.svg
title: The Future is Closer
